### ISSUE TITLE
NameError: global name 'ConnectionError' is not defined

### ISSUE THREAD

**Issue by interneteur** [timotheus/ebaysdk-python#106]
Not sure why I am getting this.  

Here is the code I'm using 
```
    try:
        ebay_api = Finding(config_file='myebay.yaml')
        response = ebay_api.execute('findItemsAdvanced', {'keywords': 'Python'})
        print(response.dict())
    except ConnectionError as e:
        print(e)
        print(e.response.dict())

```

And here is the traceroute

```
Traceback (most recent call last):
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/john/.virtualenvs/in5/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/john/Scripts/Python/in5/in5.py", line 72, in eb
    except ConnectionError as e:
NameError: global name 'ConnectionError' is not defined
```

**Comment by interneteur** [comment]
Ok so I took out the try, and now I'm getting a socket timeout.  I figure it must be due to my internet connection.
