### ISSUE TITLE
AttributeError: 'ResponseDataObject' object has no attribute 'Ack'

### ISSUE THREAD

**Issue by zzxworld** [timotheus/ebaysdk-python#107]
version: ebaysdk==2.1.1
~~~
DEBUG:requests.packages.urllib3.connectionpool:"POST /ws/api.dll HTTP/1.1" 503 62
DEBUG:ebaysdk:RESPONSE (0de965b7-cb58-4244-a186-6ae300836d54):
DEBUG:ebaysdk:elapsed time=0:00:01.431655
DEBUG:ebaysdk:status code=503
DEBUG:ebaysdk:headers={'content-length': '62', 'x-ebay-esb-guid': 'urn:uuid:7E2CE86C86E57ECA9A1437028295474', 'x-ebay-esb-call-name': 'AddItem', 'connection': 'Close', 'pragma': 'no-cache', 'cache-control': 'no-cache,no-store', 'date': 'Fri, 19 Jun 2015 04:04:48 GMT', 'x-ebay-esb-app-name': 'EKKOf84ce-aae1-48e2-a826-b2cdfb0f85c', 'content-type': 'application/octet-stream', 'x-ebay-esb-siteid': '0'}
DEBUG:ebaysdk:content=<html><body><b>Http/1.1 Service Unavailable</b></body> </html>
Traceback (most recent call last):
  File "./test.py", line 56, in <module>
    main()
  File "./test.py", line 49, in main
    addItem()
  File "./test.py", line 34, in addItem
    image_url_list = ['http://i.ebayimg.sandbox.ebay.com/00/s/MTIwMFgxNjAw/z/qU0AAOSw6XdVf6md/$_1.JPG?set_id=8800005007'])
  File "/Users/zzxworld/Projects/office/src/app/modules/shop/ebay.py", line 313, in addEbayItem
    api.execute('AddItem', {'Item': item_data})
  File "/Users/zzxworld/.virtualenvs/office/lib/python2.7/site-packages/ebaysdk/connection.py", line 123, in execute
    self.error_check()
  File "/Users/zzxworld/.virtualenvs/office/lib/python2.7/site-packages/ebaysdk/connection.py", line 193, in error_check
    estr = self.error()
  File "/Users/zzxworld/.virtualenvs/office/lib/python2.7/site-packages/ebaysdk/connection.py", line 305, in error
    error_array.extend(self._get_resp_body_errors())
  File "/Users/zzxworld/.virtualenvs/office/lib/python2.7/site-packages/ebaysdk/trading/__init__.py", line 786, in _get_resp_body_errors
    if self.response.reply.Ack == 'Failure':
AttributeError: 'ResponseDataObject' object has no attribute 'Ack'
~~~

**Comment by timotheus** [comment]
Is some of the debug output missing? I can't see the actual request data

**Comment by zzxworld** [comment]
sorry reply later. 
i tried this error only raise on ebay sandbox platform. is not a bug.
thanks for your work.

**Comment by macdonjo** [comment]
I also want to add that I can also confirm that this error only occurs in the sandbox and not in production. Very strange.

**Comment by reubano** [comment]
Getting same error. Why is it not a bug? Worked find in v1.

**Comment by reubano** [comment]
Just trying to run the example from the readme will trigger it.

**Comment by reubano** [comment]
NVM... I was running `shopping` Connection instead of the `finding` one.
