### ISSUE TITLE
XML Parse error with &

### ISSUE THREAD

**Issue by jmsfwk** [timotheus/ebaysdk-python#129]
When I try to execute a `ReviseItem` call including the following data:

```
...
<PrimaryCategory>
    <CategoryID>171228</CategoryID>
    <CategoryName>Books:Fiction & Literature</CategoryName>
</PrimaryCategory>
...
```

I get an error about the unescaped `&`.

```
Traceback (most recent call last):
  File "~\.virtualenvs\ebay\ebay.py", line 12, in <module>
    newresponse = api.execute('ReviseItem', item)
  File "~\ebay\lib\site-packages\ebaysdk\connection.py", line 123, in execute
    self.error_check()
  File "~\.virtualenvs\ebay\lib\site-packages\ebaysdk\connection.py", line 213, in error_check
    raise ConnectionError(estr, self.response)
ebaysdk.exception.ConnectionError: u'ReviseItem: Class: RequestError, Severity: Error, Code: 5, XML
Parse error. XML Error Text: "; nested exception is: \n\torg.xml.sax.SAXParseException: The entity
name must immediately follow the \'&\' in the entity reference.".'
```

**Comment by vwithv1602** [comment]
Can anyone help on this. Same error occurred for me while using **ReviseFixedPriceItem**

**Comment by timotheus** [comment]
https://developer.ebay.com/devzone/xml/docs/reference/ebay/ReviseFixedPriceItem.html#Request.Item.PrimaryCategory

According to the API docs you should supply CategoryName, which should fix your issue.

On a related note, I think you'll need to encode the "&" into "&amp;" for it to parse correctly.

**Comment by bushjt987** [comment]
For anyone else with this issue, the solution is to set 'escape_html' to True when you initialize your Connection session.

```from ebaysdk.trading import Connection as Trading
session = Trading(appid=<EBAY_API_KEY>, devid=settings.EBAY_DEV_ID, certid=<EBAY_SECRET>, config_file=None, iaf_token=<ebay_user_access_token>, compatibility=<EBAY_API_VERSION>, debug=False, escape_xml=True)
