### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by blueboy121** [timotheus/ebaysdk-python#141]
This is as simple as a code that I can run but it still isn't working. Please help! I'm running Python 3.5.1 on a 64-bit Windows. This is the code:

>import ebaysdk
from ebaysdk.trading import Connection as Trading

>api = Trading(domain='api.sandbox.ebay.com',  appid="", devid="", certid="", token="",config_file=None)

>api.execute("GetFeedback", {"UserID": "testuser_blueboy121"})

I'm receiving this error:

> Traceback (most recent call last):
  File "C:\Python35\Scripts\Practice\Ebay\ebayAcctControl.py", line 7, in <module>
    api.execute("GetFeedback", {"UserID": "testuser_blueboy121"})
  File "C:\Python35\lib\site-packages\ebaysdk\connection.py", line 122, in execute
    self.process_response()
  File "C:\Python35\lib\site-packages\ebaysdk\connection.py", line 200, in process_response
    parse_response=parse_response)
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 151, in __init__
    datetime_nodes=copy.copy(datetime_nodes))
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 23, in __init__
    self._load_dict(mydict, list(datetime_nodes))
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 59, in _load_dict
    o = ResponseDataObject(a[1], datetime_nodes)
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 23, in __init__
    self._load_dict(mydict, list(datetime_nodes))
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 59, in _load_dict
    o = ResponseDataObject(a[1], datetime_nodes)
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 23, in __init__
    self._load_dict(mydict, list(datetime_nodes))
  File "C:\Python35\lib\site-packages\ebaysdk\response.py", line 65, in _load_dict
    if i is None or isinstance(i, str) or isinstance(i, unicode):
NameError: name 'unicode' is not defined

What am I doing wrong?

**Comment by blueboy121** [comment]
OK so I re-installed ebaysdk using the master files and it fixed this error.
https://github.com/timotheus/ebaysdk-python/blob/master/INSTALL
