### ISSUE TITLE
Invalid headers Exception with requests >= 2.11

### ISSUE THREAD

**Issue by 77cc33** [timotheus/ebaysdk-python#171]
Starting from version 2.11 requests library accepts only strings in headers keys/values, so it breaks current implementation in ebay sdk as you are sending some values as int

```python
/site-packages/requests/utils.py", line 796, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 22, in <module>
    'DetailLevel': 'ReturnAll'}
  File "/python3.5/site-packages/ebaysdk/connection.py", line 119, in execute
    self.build_request(verb, data, verb_attrs, files)
  File "/python3.5/site-packages/ebaysdk/connection.py", line 159, in build_request
    self.request = request.prepare()
  File "/python3.5/site-packages/requests/models.py", line 251, in prepare
    hooks=self.hooks,
  File "python3.5/site-packages/requests/models.py", line 295, in prepare
    self.prepare_headers(headers)
  File "/python3.5/site-packages/requests/models.py", line 409, in prepare_headers
    check_header_validity(header)
  File "/python3.5/site-packages/requests/utils.py", line 800, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 3 must be of type str or bytes, not <class 'int'>
```

more information here https://github.com/kennethreitz/requests/issues/3512

**Comment by 77cc33** [comment]
sorry, I just found this ticket https://github.com/timotheus/ebaysdk-python/issues/162

It's just not clear, that from now siteid  should be STRING type
