### ISSUE TITLE
sample code demonstrating "find_items_by_ids" returns "Header value None must be of type str or bytes"

### ISSUE THREAD

**Issue by acegallagher** [timotheus/ebaysdk-python#177]
Hey there. I just installed the pythonsdk for the first time and was trying out some of the sample code when I ran into a strange error. I tried debugging it but I'm not quite skilled enough to be of great help. I cloned your repository, filled out an ebay.yaml config file and got to hacking. Using both python 2.7 and 3.5 The sample crashes, without any modifications, with the following traceback:

`oTraceback (most recent call last):
  File "EbayTrawler.py", line 89, in <module>
    run(opts)
  File "EbayTrawler.py", line 74, in run
    records = api.find_items_by_ids(itemIds)
  File "/usr/lib/python2.7/site-packages/ebaysdk-2.1.4-py2.7.egg/ebaysdk/soa/finditem.py", line 115, in find_items_by_ids
    return self.findItemsByIds(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ebaysdk-2.1.4-py2.7.egg/ebaysdk/soa/finditem.py", line 84, in findItemsByIds
    self.execute('findItemsByIds', args)
  File "/usr/lib/python2.7/site-packages/ebaysdk-2.1.4-py2.7.egg/ebaysdk/connection.py", line 119, in execute
    self.build_request(verb, data, verb_attrs, files)
  File "/usr/lib/python2.7/site-packages/ebaysdk-2.1.4-py2.7.egg/ebaysdk/connection.py", line 159, in build_request
    self.request = request.prepare()
  File "/usr/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 257, in prepare
    hooks=self.hooks,
  File "/usr/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 303, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/models.py", line 427, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python2.7/site-packages/requests-2.12.4-py2.7.egg/requests/utils.py", line 796, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value None must be of type str or bytes, not <type 'NoneType'>
`

**Comment by derekmckinnon** [comment]
It might help if you supply the code you wrote to assist with finding the problem. I know you've said that you're using the sample, but the traceback indicates that you may have written more code (ex. the `run` function). BTW, you can use triple backticks (```) before and after your code snippet to make it readable here (no need to upload files).

**Comment by XinyuHou** [comment]
This is supposed to be fix in #162. But I still experience the problem on my Mac with ebaysdk 2.1.4 installed.
