### ISSUE TITLE
error Uploading Images with UploadSiteHostedPictures

### ISSUE THREAD

**Issue by darecAdirondack** [timotheus/ebaysdk-python#219]
My programs had no problem at all uploading images, and the last time i checked a specific version of my code, the images still uploaded perfectly fine. but for what seems to be no reason at all, im getting an error now when trying to upload images with UploadSiteHostedPictures to the sandbox. it seems like it works in production mode, but im getting some other weird error there now too. when i used an old batch of code that previously worked, it gives me the same error. I tried getting a new sandbox keyset to no avail, as well as checking the correct imagepath etc etc. i cant think of anything else that would have changed?

my code:

```
image = 'myimage.jpg'
im = Image.open(image)
im.copy().save(image)
im.close()

with Image.open(image) as im:
    # scale the image to a suitable size
    # use thumbnail to scale to the bounding box
    # use resize if you want to calculate the dims 

    with io.BytesIO() as fp:
        im.save(fp, "JPEG")

        files = {'file': ('EbayImage', fp.getvalue())}
        pictureData = {
            "WarningLevel": "High",
            "PictureSet":'Supersize',
            "PictureName": ''}
        
        response = Api_Trading.execute('UploadSiteHostedPictures', pictureData, files=files)
        soup = BeautifulSoup(response.content,'lxml')
        listPictureDetails.append(soup.fullurl.text)
    
im = Image.open(image)
im.copy().save(image)
im.close()
```

resulting error:
`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    sandbox()
  File "C:\Python\Projects\juvicaDesktop\juvicaDesktop_AddItem-0.py", line 70, in sandbox
    ListItems('sandbox')
  File "C:\Python\Projects\juvicaDesktop\juvicaDesktop_AddItem-0.py", line 199, in ListItems
    imageresponse = Api_Trading.execute('UploadSiteHostedPictures', pictureData, files=files)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\ebaysdk\connection.py", line 124, in execute
    self.error_check()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\ebaysdk\connection.py", line 209, in error_check
    estr = self.error()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\ebaysdk\connection.py", line 321, in error
    error_array.extend(self._get_resp_body_errors())
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\ebaysdk\trading\__init__.py", line 736, in _get_resp_body_errors
    dom = self.response.dom()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\ebaysdk\response.py", line 233, in dom
    return self._dom
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\ebaysdk\response.py", line 220, in __getattr__
    return getattr(self._obj, name)
AttributeError: 'Response' object has no attribute '_dom'`

the error is at the line close the end: `Api_Trading.execute('UploadSiteHostedPictures', pictureData, files=files)`
where the only thing i can think of, is that my variable `files` is giving the image in a format that the api for some reason isnt interacting correctly with?

**Comment by darecAdirondack** [comment]
incomplete
