### ISSUE TITLE
doctest.UnexpectedException: <DocTest ebaysdk.finding.Connection from

### ISSUE THREAD

**Issue by zhibeen** [timotheus/ebaysdk-python#236]
i test the test module，

But , the sdk have error.

i have save the the ebay.yaml in the current file!

andy

how can i do to save this error

...E.E..EE.
======================================================================
ERROR: test_run_doctest_finding (__main__.TestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 72, in test_run_doctest_finding
    self.doctest(ebaysdk.finding)
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 39, in doctest
    doctest.testmod(module, raise_on_error=True, verbose=False)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1951, in testmod
    runner.run(test)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1839, in run
    r = DocTestRunner.run(self, test, compileflags, out, False)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1476, in run
    return self.__run(test, compileflags, out)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1382, in __run
    exception)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1845, in report_unexpected_exception
    raise UnexpectedException(test, example, exc_info)
doctest.UnexpectedException: <DocTest ebaysdk.finding.Connection from F:\python\ebaysdk\ll_venv\lib\site-packages\ebaysdk\finding\__init__.py:18 (5 examples)>

======================================================================
ERROR: test_run_doctest_merchandising (__main__.TestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 69, in test_run_doctest_merchandising
    self.doctest(ebaysdk.merchandising)
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 39, in doctest
    doctest.testmod(module, raise_on_error=True, verbose=False)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1951, in testmod
    runner.run(test)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1839, in run
    r = DocTestRunner.run(self, test, compileflags, out, False)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1476, in run
    return self.__run(test, compileflags, out)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1382, in __run
    exception)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1845, in report_unexpected_exception
    raise UnexpectedException(test, example, exc_info)
doctest.UnexpectedException: <DocTest ebaysdk.merchandising.Connection from F:\python\ebaysdk\ll_venv\lib\site-packages\ebaysdk\merchandising\__init__.py:15 (4 examples)>

======================================================================
ERROR: test_run_doctest_shopping (__main__.TestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\YIDE-007\AppData\Roaming\Python\Python36\site-packages\requests\utils.py", line 868, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 60, in test_run_doctest_shopping
    'IncludeSelector': ['ChildCategories']})
  File "F:\python\ebaysdk\ll_venv\lib\site-packages\ebaysdk\connection.py", line 122, in execute
    self.build_request(verb, data, verb_attrs, files)
  File "F:\python\ebaysdk\ll_venv\lib\site-packages\ebaysdk\connection.py", line 162, in build_request
    self.request = request.prepare()
  File "C:\Users\YIDE-007\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 259, in prepare
    hooks=self.hooks,
  File "C:\Users\YIDE-007\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 306, in prepare
    self.prepare_headers(headers)
  File "C:\Users\YIDE-007\AppData\Roaming\Python\Python36\site-packages\requests\models.py", line 440, in prepare_headers
    check_header_validity(header)
  File "C:\Users\YIDE-007\AppData\Roaming\Python\Python36\site-packages\requests\utils.py", line 872, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {X-EBAY-API-APP-ID: None} must be of type str or bytes, not <class 'NoneType'>

======================================================================
ERROR: test_run_doctest_trading (__main__.TestBase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 66, in test_run_doctest_trading
    self.doctest(ebaysdk.trading)
  File "F:/python/ebaysdk/ll_venv/Lib/site-packages/tests/test_base.py", line 39, in doctest
    doctest.testmod(module, raise_on_error=True, verbose=False)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1951, in testmod
    runner.run(test)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1839, in run
    r = DocTestRunner.run(self, test, compileflags, out, False)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1476, in run
    return self.__run(test, compileflags, out)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1382, in __run
    exception)
  File "D:\Programs\Python\Python36\lib\doctest.py", line 1845, in report_unexpected_exception
    raise UnexpectedException(test, example, exc_info)
doctest.UnexpectedException: <DocTest ebaysdk.trading.Connection from F:\python\ebaysdk\ll_venv\lib\site-packages\ebaysdk\trading\__init__.py:18 (15 examples)>

----------------------------------------------------------------------
Ran 11 tests in 0.067s

FAILED (errors=4)

**Comment by ZhigangQi** [comment]
Hi,i don't know if you will see the comment.Did you figured the issue out？
