### ISSUE TITLE
met 'zip_safe flag not set ; analyzing archive contents...' error when I install ebaySDK

### ISSUE THREAD

**Issue by anzhuo** [timotheus/ebaysdk-python#240]
My System is

Window 7 64 bits
Python 3.7  64 bits

E:\Python\ebaysdk-python-master>python setup.py install
running install
running bdist_egg
running egg_info
writing ebaysdk.egg-info\PKG-INFO
writing dependency_links to ebaysdk.egg-info\dependency_links.txt
writing requirements to ebaysdk.egg-info\requires.txt
writing top-level names to ebaysdk.egg-info\top_level.txt
reading manifest file 'ebaysdk.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ebaysdk.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying ebaysdk.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying ebaysdk.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ebaysdk.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-
NFO
copying ebaysdk.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ebaysdk.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    'Programming Language :: Python :: 3.5',
  File "E:\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\Python\Python37\lib\site-packages\setuptools\command\install.py", li
e 67, in run
    self.do_egg_install()
  File "E:\Python\Python37\lib\site-packages\setuptools\command\install.py", li
e 109, in do_egg_install
    self.run_command('bdist_egg')
  File "E:\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py",
ine 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "E:\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py",
ine 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "E:\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py",
ine 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "E:\Python\Python37\lib\site-packages\setuptools\command\bdist_egg.py",
ine 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
![error](https://user-images.githubusercontent.com/1036416/38744930-b828ebee-3f75-11e8-9459-094b661c74f9.jpg)

**Comment by anzhuo** [comment]
How can I fix it ? I'm new to python :）

**Comment by procurator5** [comment]
If you get that error, the compiled version of the Python module (the .pyc file) is corrupt probably. Gentoo Linux provides python-updater, but in Debian the easier way to fix: just delete the .pyc file. If you don't know the pyc, just delete all of them (as root):

`find /usr -name '*.pyc' -delete`

**Comment by anzhuo** [comment]
I use Python 3.7 32 bits to fix this problem
