### ISSUE TITLE
GetUser example gives ConnectionRefusedError ([WinError 10061])

### ISSUE THREAD

**Issue by HansvdLaan** [timotheus/ebaysdk-python#254]
I’m trying to get the Trading API example working. Unfortunately, I can’t get the example working for my sandbox account. I get the same results for both my German and American sandbox account. Being signed-in/out in my browser made no difference.

My implementation (I just added config_file=None):
```python
from ebaysdk.exception import ConnectionError
from ebaysdk.finding import Connection

def getUser(a, devid, certid, token):
    try:
        api = Connection(domain='api.sandbox.ebay.com',
        appid=appid, devid=devid, certid=certid, token=token, config_file=None)
        response = api.execute('GetUser', {})
        print(response.dict())
        print(response.reply)

    except ConnectionError as e:
        print(e)
        print(e.response.dict())

appid = "my_appid"
devid = "my_devid"
certid = "my_certid"
token = "testuser_token"

getUser(appid, devid, certid, token)
```

The stacktrace:
```
`C:\Users\user\AppData\Local\Programs\Python\Python36-32\python.exe C:\Users\user\PycharmProjects\ebayscripts\getUser.py
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Kan geen verbinding maken omdat de doelcomputer de verbinding actief heeft geweigerd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 196, in connect
    conn = self._new_conn()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x038F0A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api.sandbox.ebay.com', port=80): Max retries exceeded with url: /services/search/FindingService/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x038F0A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\ebayscripts\getUser.py", line 21, in <module>
    getUser(appid, devid, certid, token)
  File "C:\Users\user\PycharmProjects\ebayscripts\getUser.py", line 8, in getUser
    response = api.execute('GetUser', {})
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ebaysdk\connection.py", line 123, in execute
    self.execute_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ebaysdk\connection.py", line 193, in execute_request
    allow_redirects=True
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.sandbox.ebay.com', port=80): Max retries exceeded with url: /services/search/FindingService/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x038F0A50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
```

**Comment by ozzstrich** [comment]
Hi, did you find a fix? Trying to do this with production, not sandbox btw

**Comment by HansvdLaan** [comment]
No, I decided to drop this SDK. It's much easier to make API calls directly.

If you're curious about how to get started with this, this tutorial might be usefull:
[Using Postman To Connect To The eBay API](http://devbay.net/blog/2015/03/22/using-postman-to-connect-to-the-ebay-api/)

**Comment by ozzstrich** [comment]
Brilliant, thank you!
