### ISSUE TITLE
Can't authenticate using example on production

### ISSUE THREAD

**Issue by lacostenycoder** [timotheus/ebaysdk-python#269]
Using the basic code example here:

```
from ebaysdk.finding import Connection as Finding
from ebaysdk.exception import ConnectionError

try:
    api = Finding(config_file='ebay.yaml')
    response = api.execute('findItemsAdvanced', {'keywords': 'Python'})
    print(response.dict())
except ConnectionError as e:
    print(e)
    print(e.response.dict())
```

my ebay.yaml looks like this, obviously I've left out my real credentials for security.
```
appid:  <MY_ID>
certid:  <MY_ID>
devid:  <MY_ID>
```

I keep getting  this trace error:

```
Traceback (most recent call last):
  File "prod.py", line 6, in <module>
    response = api.execute('findItemsAdvanced', {'keywords': 'Python'})
  File "/Users/monkeybutt/.pyenv/versions/2.7.15/lib/python2.7/site-packages/ebaysdk-2.1.5-py2.7.egg/ebaysdk/connection.py", line 122, in execute
    self.build_request(verb, data, verb_attrs, files)
  File "/Users/monkeybutt/.pyenv/versions/2.7.15/lib/python2.7/site-packages/ebaysdk-2.1.5-py2.7.egg/ebaysdk/connection.py", line 162, in build_request
    self.request = request.prepare()
  File "/Users/monkeybutt/.pyenv/versions/2.7.15/lib/python2.7/site-packages/requests/models.py", line 267, in prepare
    hooks=self.hooks,
  File "/Users/monkeybutt/.pyenv/versions/2.7.15/lib/python2.7/site-packages/requests/models.py", line 314, in prepare
    self.prepare_headers(headers)
  File "/Users/monkeybutt/.pyenv/versions/2.7.15/lib/python2.7/site-packages/requests/models.py", line 448, in prepare_headers
    check_header_validity(header)
  File "/Users/monkeybutt/.pyenv/versions/2.7.15/lib/python2.7/site-packages/requests/utils.py", line 945, in check_header_validity
    "bytes, not %s" % (name, value, type(value)))
requests.exceptions.InvalidHeader: Value for header {X-EBAY-SOA-SECURITY-APPNAME: None} must be of type str or bytes, not <type 'NoneType'>
```

**Comment by bb14742** [comment]
I don't know whether this will help resolve your issue with findItemsAdvanced, but PART I and PART II of this tutorial helped me get started with findItemsByKeywords. https://linuxconfig.org/introduction-to-ebay-api-with-python-obtaining-keys-and-accessing-the-sandbox-part-1
