### ISSUE TITLE
An existing connection was forcibly closed

### ISSUE THREAD

**Issue by shootin4aces** [timotheus/ebaysdk-python#303]
I have had this script up and working for months and have made no changes. however suddenly I am getting this error almost every single time I run the script. Anyone have any idea why???? Please feel free to ask any questions to help point me in the right direction but I am at a complete loss here

Traceback (most recent call last):
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\narul\Documents\MoneyTime\EbayApiFunctions.py", line 36, in MakeApiRequest
    response_title = api.execute('findCompletedItems', requestApi)
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\ebaysdk\connection.py", line 123, in execute
    self.execute_request()
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\ebaysdk\connection.py", line 193, in execute_request
    allow_redirects=True
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\narul\Documents\ClearancePalet\venv\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Process finished with exit code 1

**Comment by nickconvery** [comment]
I've just started using the sdk today and ran into the same error when using the examples from the documentation. eBay has recently dropped support for http from the Finding API so you need to set https to True when initiating the Connection object. https://developer.ebay.com/news/https-only-finding-api

**Comment by shootin4aces** [comment]
> I've just started using the sdk today and ran into the same error when using the examples from the documentation. eBay has recently dropped support for http from the Finding API so you need to set https to True when initiating the Connection object. https://developer.ebay.com/news/https-only-finding-api

OMG... thankyou!!!! appreciate it greatly! That is exactly what it was!!!! Up and running again!!!!
