### ISSUE TITLE
AttributeError: 'Response' object has no attribute '_dom'

### ISSUE THREAD

**Issue by oerp-odoo** [timotheus/ebaysdk-python#84]
I get mentioned error when running this piece of code:

``` python
from ebaysdk.shopping import Connection as Shopping
api = Trading(domain='api.sandbox.ebay.com', config_file="ebay.yaml")
shopping = Shopping(domain="svcs.sandbox.ebay.com", config_file="ebay.yaml")
response = shopping.execute('FindPopularItems',
           {'QueryKeywords': 'Python'})
print response.disct()
```

Whole error:

``` python
Traceback (most recent call last):
  File "ebay-test.py", line 8, in <module>
    {'QueryKeywords': 'Python'})
  File "/usr/local/lib/python2.7/dist-packages/ebaysdk-2.1.0-py2.7.egg/ebaysdk/connection.py", line 123, in execute
    self.error_check()
  File "/usr/local/lib/python2.7/dist-packages/ebaysdk-2.1.0-py2.7.egg/ebaysdk/connection.py", line 193, in error_check
    estr = self.error()
  File "/usr/local/lib/python2.7/dist-packages/ebaysdk-2.1.0-py2.7.egg/ebaysdk/connection.py", line 305, in error
    error_array.extend(self._get_resp_body_errors())
  File "/usr/local/lib/python2.7/dist-packages/ebaysdk-2.1.0-py2.7.egg/ebaysdk/shopping/__init__.py", line 188, in _get_resp_body_errors
    dom = self.response.dom()
  File "/usr/local/lib/python2.7/dist-packages/ebaysdk-2.1.0-py2.7.egg/ebaysdk/response.py", line 229, in dom
    return self._dom
  File "/usr/local/lib/python2.7/dist-packages/ebaysdk-2.1.0-py2.7.egg/ebaysdk/response.py", line 216, in __getattr__
    return getattr(self._obj, name)
AttributeError: 'Response' object has no attribute '_dom'
```

**Comment by FintanH** [comment]
Is there a reason this error would appear spontaneously? I had a script running using the API for a few days and then this suddenly appeared.

**Comment by timotheus** [comment]
@FintanH can you share the error? (enable debug and send the entire request/response)

**Comment by FintanH** [comment]
@timotheus: I'll do my best. As I said it was spontaneous in its appearance, 99.99% of the time it works perfectly and was very unexpected.

**Comment by FintanH** [comment]
@timotheus I have an example request that bombed out with the AttributeError but subsequently was able to retrieve the item. 

``` python
from ebaysdk.shopping import Connection as Shopping

pars = {"ItemID": "162389043741", "version": 981, "IncludeSelector": "Variations"}
r = Shopping(appid=myappid, config_file=None).execute('GetSingleItem', pars)
print(r.dict())
```

Could this be something to do with the API not receiving the call for some reason?

**Comment by afteriwoof** [comment]
I have this error and cannot figure out a solution even with your discussion here. It works 99% of the time on my macbook but this error appears every attempt to run it on linux server. I have checked proxy settings, credentials, domain specifications, etc. but no luck. Any further ideas please?

**Comment by jankins** [comment]
Try to add `https=True`. E.g. Shopping(domain="svcs.sandbox.ebay.com", config_file="ebay.yaml", https=True)

The default one doesn't use HTTPS and it returns HTML not XML, which cause the parsing error.

**Comment by codetoexplore** [comment]
above solution worked for me
