### ISSUE TITLE
README doesn't mention ebaysdk.finding.Connection requires config file

### ISSUE THREAD

**Issue by davidmarin** [timotheus/ebaysdk-python#92]
```python
>>> from ebaysdk.finding import Connection
>>> api = Connection()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidmarin/git/spendright/python/venv/lib/python2.7/site-packages/ebaysdk/finding/__init__.py", line 70, in __init__
    config_file=kwargs.get('config_file', 'ebay.yaml'))
  File "/Users/davidmarin/git/spendright/python/venv/lib/python2.7/site-packages/ebaysdk/config.py", line 39, in __init__
    self._populate_yaml_defaults()
  File "/Users/davidmarin/git/spendright/python/venv/lib/python2.7/site-packages/ebaysdk/config.py", line 72, in _populate_yaml_defaults
    raise ConnectionConfigError('config file %s not found' % self.config_file)
ebaysdk.exception.ConnectionConfigError: u'config file ebay.yaml not found'
```

Is this the intended behavior? The README doesn't say anything about needing `ebay.yaml`. Observed this behavior in both 2.0.0 and 2.1.0.

The workaround is to explicitly disable the config file:

```python
>>> api = Connection(config_file=None)
```

**Comment by mw44118** [comment]
It seems like this is what the README should show:

    ebaysdk.finding.Connection(appid="...", config_file=None)

**Comment by timotheus** [comment]
added to the README
