### ISSUE TITLE
does not XML-escape strings

### ISSUE THREAD

**Issue by coyotemarin** [timotheus/ebaysdk-python#93]
It looks like you have to explicitly XML-escape strings you pass to the API. For example:

``` python
>>> from ebaysdk.finding import Connection; from os import environ
>>> api = Connection(appid=environ['EBAY_APP_ID'], config_file=None)
>>> response = api.execute('findItemsAdvanced', {'keywords': 'Graham & Spencer'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidmarin/git/spendright/python/venv/lib/python2.7/site-packages/ebaysdk/connection.py", line 123, in execute
    self.error_check()
  File "/Users/davidmarin/git/spendright/python/venv/lib/python2.7/site-packages/ebaysdk/connection.py", line 197, in error_check
    raise ConnectionError(estr, self.response)
ebaysdk.exception.ConnectionError: u"findItemsAdvanced: Internal Server Error, Domain: CoreRuntime, Severity: Error, errorId: 2030, Internal error: [com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character ' ' (code 32) (missing name?)\n at javax.xml.stream.SerializableLocation@288b288b"
>>> response = api.execute('findItemsAdvanced', {'keywords': 'Graham &amp; Spencer'})
```

Is there any reason for `ebaysdk` not to auto-escape? To maintain backwards compatibility, you can leave alone any string that can be XML-unescaped (so that you don't end up double-escaping strings).

Currently working around this by wrapping every string I pass to the API with `xml.sax.saxutils.escape()`.

**Comment by timotheus** [comment]
I suppose it could, but in my experience calling eBay API I rarely need to escape. Adding auto escaping for the request body would incur a performance cost that I'm not sure is worth it. 

Maybe this could be a flag to the constructor (off by default). Would that work?
